#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/install-slideshow.sh --hash-url URL --video-url URL

Options:
  --hash-url URL     Remote hash.txt URL
  --video-url URL    Remote MP4 URL
  --skip-packages    Do not install vlc/curl with apt-get
  -h, --help         Show this help
USAGE
}

HASH_URL=""
VIDEO_URL=""
INSTALL_PACKAGES="yes"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --hash-url)
      HASH_URL="${2:-}"
      shift 2
      ;;
    --video-url)
      VIDEO_URL="${2:-}"
      shift 2
      ;;
    --skip-packages)
      INSTALL_PACKAGES="no"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$HASH_URL" || -z "$VIDEO_URL" ]]; then
  echo "Both --hash-url and --video-url are required." >&2
  usage >&2
  exit 2
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"

if [[ "$INSTALL_PACKAGES" == "yes" ]]; then
  sudo apt-get update
  sudo apt-get install -y vlc curl
fi

install -d \
  "$HOME/.local/bin" \
  "$HOME/.config/autostart" \
  "$HOME/.config/slideshow" \
  "$HOME/.config/systemd/user"

install -m 0755 "$REPO_DIR/scripts/slideshow-update.sh" "$HOME/.local/bin/slideshow-update"
install -m 0755 "$REPO_DIR/scripts/slideshow-session-start.sh" "$HOME/.local/bin/slideshow-session-start"

install -m 0644 "$REPO_DIR/systemd/user/slideshow-player.service" "$HOME/.config/systemd/user/"
install -m 0644 "$REPO_DIR/systemd/user/slideshow-update.service" "$HOME/.config/systemd/user/"
install -m 0644 "$REPO_DIR/systemd/user/slideshow-update.timer" "$HOME/.config/systemd/user/"

{
  printf '# Generated by scripts/install-slideshow.sh\n'
  printf 'REMOTE_HASH_URL=%q\n' "$HASH_URL"
  printf 'REMOTE_VIDEO_URL=%q\n' "$VIDEO_URL"
  printf 'DOWNLOAD_RETRIES=%q\n' "3"
} > "$HOME/.config/slideshow/slideshow.conf"

cat > "$HOME/.config/autostart/slideshow-session.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Slideshow Startup
Comment=Start the unattended VLC slideshow updater
Exec=$HOME/.local/bin/slideshow-session-start
Terminal=false
X-GNOME-Autostart-enabled=true
EOF

export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

systemctl --user daemon-reload
systemctl --user enable --now slideshow-update.timer

if [[ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ]]; then
  "$HOME/.local/bin/slideshow-session-start"
else
  systemctl --user start slideshow-update.service
  echo "No desktop display environment detected. VLC will start automatically at the next graphical auto-login."
fi

echo "Slideshow updater installed. The auto-login desktop session will run it unattended on boot."
